securityRules:
  REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf: |-
    # skip health check
    SecRule REQUEST_URI "@streq /healthz" "id:10001,phase:1,pass,nolog,ctl:ruleEngine=Off"
    
    # GeoIP
    SecGeoLookupDb /etc/modsecurity.d/geoip/geoip-country.mmdb
    SecRule REMOTE_ADDR "@geoLookup" "phase:1,id:155,pass"

geoip:
  enabled: true
  downloadUrl: "https://download.maxmind.com/geoip/databases/GeoLite2-Country/download?suffix=tar.gz"
  downloadToken: "accountId:licenseKey"

  downloadCommand:
    - sh
    - -c
    - >
      if [ ! -f /geoip/geoip-country.mmdb ] || ! find /geoip/geoip-country.mmdb -mtime +7 -exec false {} +; then
        echo "GeoIP database is missing or older than 7 days. Downloading new version...";
        rm -f /geoip/geoip-country.mmdb;
        curl --fail -L -o /geoip/geolite.tar.gz -u "${GEOIP_DOWNLOAD_TOKEN}" "${GEOIP_DOWNLOAD_URL}" || exit 1;
        tar -xzf /geoip/geolite.tar.gz --strip-components=1 -C /geoip;
        rm /geoip/geolite.tar.gz;
        mv /geoip/GeoLite*.mmdb /geoip/geoip-country.mmdb;
        touch /geoip/geoip-country.mmdb;
        echo "GeoIP has been updated.";
      else
        echo "GeoIP database is up to date.";
      fi
